"""Stage 2 validation: CFDL pseudo-Jacobian estimation and MFAC tracking.

The controller is model-free, so we validate it against *unknown-to-the-
controller* synthetic plants and check the properties guaranteed by the
theory: PJM identification under persistent excitation, and monotone error
reduction / setpoint tracking in closed loop.
"""

import numpy as np
import pytest

from cfdl_mfac_ncp_td3.config import MFACConfig
from cfdl_mfac_ncp_td3.controllers import PseudoJacobianEstimator, CFDLMFAC


def test_pjm_identifies_static_gain():
    """With persistent excitation the PJM converges to the true gain matrix."""

    rng = np.random.default_rng(0)
    G = np.array([[2.0, 0.3], [-0.5, 1.5]])
    est = PseudoJacobianEstimator(2, 2, MFACConfig(eta=1.0, mu=0.1, phi_init=1.0))
    du_prev = np.zeros(2)
    for _ in range(2000):
        du = rng.normal(size=2)
        dy = G @ du  # response generated by the (hidden) true gain
        est.update(dy, du)
    # Drive a final informative increment to read out the estimate.
    err = np.linalg.norm(est.phi - G) / np.linalg.norm(G)
    assert err < 0.05, f"PJM failed to identify gain, rel-err={err:.3f}"


def test_mfac_tracks_constant_setpoint_stable_plant():
    """MFAC drives a stable diagonal plant y(k+1)=a*y(k)+b*u(k) to the setpoint.

    A stable plant settles under constant input, satisfying the CFDL
    generalized-Lipschitz condition (a pure integrator does not).
    """

    a = np.diag([0.7, 0.6, 0.8])
    b = np.diag([0.4, 0.25, 0.6])
    ctrl = CFDLMFAC(3, 3, MFACConfig(rho=0.6, lam=0.5, eta=1.0, mu=1.0, u_limit=2.0))
    y = np.zeros(3)
    y_ref = np.array([1.0, -0.5, 0.8])
    for _ in range(800):
        u = ctrl.control(y, y_ref)
        y = a @ y + b @ u
    assert np.linalg.norm(y - y_ref) < 1e-2, f"tracking error too large: {y - y_ref}"


def test_mfac_tracks_stable_linear_plant():
    """MFAC tracks a setpoint on a coupled stable first-order MIMO plant."""

    A = np.array([[0.8, 0.05], [-0.04, 0.85]])
    B = np.array([[0.5, 0.0], [0.1, 0.4]])
    ctrl = CFDLMFAC(2, 2, MFACConfig(rho=0.5, lam=1.0, u_limit=3.0))
    y = np.zeros(2)
    y_ref = np.array([0.6, -0.3])
    errs = []
    for _ in range(600):
        u = ctrl.control(y, y_ref)
        y = A @ y + B @ u
        errs.append(np.linalg.norm(y - y_ref))
    assert errs[-1] < 0.02, f"steady-state error {errs[-1]:.4f}"
    assert errs[-1] < errs[10], "error should decrease over the episode"


def test_mfac_error_is_monotone_on_average():
    a = np.diag([0.7, 0.7])
    b = np.diag([0.5, 0.5])
    ctrl = CFDLMFAC(2, 2, MFACConfig(rho=0.5, lam=1.0))
    y = np.zeros(2)
    y_ref = np.ones(2)
    errs = []
    for _ in range(300):
        u = ctrl.control(y, y_ref)
        y = a @ y + b @ u
        errs.append(np.linalg.norm(y - y_ref))
    # First-third vs last-third mean error must drop substantially.
    first = np.mean(errs[:100])
    last = np.mean(errs[-100:])
    assert last < 0.1 * first


def test_estimator_reset_on_degenerate_input():
    est = PseudoJacobianEstimator(2, 2, MFACConfig(epsilon=1e-3, phi_init=1.0))
    phi0 = est.phi.copy()
    # A near-zero input increment must trigger a reset to the initial PJM.
    est.phi = np.array([[5.0, 1.0], [2.0, 3.0]])
    est.update(np.zeros(2), np.zeros(2))
    assert np.allclose(est.phi, phi0), "PJM should reset on degenerate input"


def test_control_respects_bounds():
    ctrl = CFDLMFAC(
        2, 2, MFACConfig(rho=2.0, lam=0.01, u_limit=10.0),
        u_bounds=(np.array([-0.5, -0.5]), np.array([0.5, 0.5])),
    )
    y = np.zeros(2)
    y_ref = np.array([100.0, -100.0])
    for _ in range(50):
        u = ctrl.control(y, y_ref)
        assert np.all(u <= 0.5 + 1e-9) and np.all(u >= -0.5 - 1e-9)


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))
